# Generated by Django 6.0.1 on 2026-02-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='portfolio.service'),
        ),
    ]
