# Generated by Django 6.0.1 on 2026-02-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_image_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='service',
        ),
    ]
