# Generated by Django 6.0.1 on 2026-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='project_used_on',
            field=models.ManyToManyField(related_name='technologies', to='portfolio.project'),
        ),
    ]
