# Generated by Django 6.0.3 on 2026-03-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_technology_project_used_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
    ]
